version: '3.8'

services: 
    frontend:
      build: ./frontend
      ports:
        - 8000:5000 # 8000 is the port on the host machine, 5000 is the port on the container
      container_name: frontend

    backend:
      build: ./backend
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
      ports: 
        - 8080:8080
      container_name: backend
      depends_on:
        - redis
        - db

    redis:
      image: redis:7.0.10-alpine
      command: redis-server
      container_name: redis
      restart: unless-stopped
      volumes:
        - redis:/data

    db:
      image: postgres:13.2-alpine
      container_name: db_postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      volumes:
        - database:/var/lib/postgresql/data

volumes:
  database:
  redis: